# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da0b94550e0ed5e6734507d60d4cebcb6403f529f96769aa19d4d51a0274803bc1ba400ddb9cc8c2eb6fcd878a82ff71a978ab7f2e8270c9c4310600a510a770

test:
  secret_key_base: f35d1c4ab51bacae951e83d4e19b830f27a0737e1e5c5ee6b25f5b83a81c75e56fff9ca123255fed831dea31a2b6760515cc6f2da73586d298e0fa9a1ea61baa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
